In [3]:
from sklearn import datasets
iris = datasets.load_iris()
digits = datasets.load_digits()

In [4]:
print(digits.data)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [5]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [6]:
from sklearn import svm
clf = svm.SVC(gamma=0.001, C=100.)
clf.fit(digits.data[:-1], digits.target[:-1])
prediction = clf.predict(digits.data[-1:])

In [7]:
prediction

array([8])

In [8]:
print(prediction)

[8]


In [9]:
digits.data[:-1]

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  6., ...,  6.,  0.,  0.],
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.]])

In [10]:
digits.data[:-1].shape

(1796, 64)

In [11]:
type(digits.data[:-1])

numpy.ndarray

In [12]:
digits.data[1]

array([ 0.,  0.,  0., 12., 13.,  5.,  0.,  0.,  0.,  0.,  0., 11., 16.,
        9.,  0.,  0.,  0.,  0.,  3., 15., 16.,  6.,  0.,  0.,  0.,  7.,
       15., 16., 16.,  2.,  0.,  0.,  0.,  0.,  1., 16., 16.,  3.,  0.,
        0.,  0.,  0.,  1., 16., 16.,  6.,  0.,  0.,  0.,  0.,  1., 16.,
       16.,  6.,  0.,  0.,  0.,  0.,  0., 11., 16., 10.,  0.,  0.])

In [13]:
digits.target[1]

1

In [14]:
import pandas as pd
from sklearn import svm

In [25]:
train_features = pd.DataFrame(digits.data, columns=range(1, len(digits.data[0])+1))
train_labels = pd.DataFrame(digits.target, columns=[1])

1
0     0
1     1
2     2
3     3
4     4
...  ..
1792  9
1793  0
1794  8
1795  9
1796  8

[1797 rows x 1 columns]

In [29]:
clf = svm.SVC(gamma=0.001, C=100.)
clf.fit(train_features, train_labels)
clf.predict(train_features)

/Users/minrengwu/anaconda3/envs/cs670/lib/python3.7/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 1, 2, ..., 8, 9, 8])

In [27]:
train_features.shape

(1797, 64)

In [28]:
train_labels.shape

(1797, 1)

In [30]:
pd.concat([train_features,train_labels],axis=1)

1    2     3     4     5     6    7    8    9    10  ...   56   57  \
0     0.0  0.0   5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1     0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2     0.0  0.0   0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
3     0.0  0.0   7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  0.0  0.0   
4     0.0  0.0   0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...   ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...   
1792  0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
1793  0.0  0.0   6.0  16.0  13.0  11.0  1.0  0.0  0.0  0.0  ...  0.0  0.0   
1794  0.0  0.0   1.0  11.0  15.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1795  0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1796  0.0  0.0  10.0  14.0   8.0   1.0  0.0  0.0  0.0  2.0  ...  0.0  0.0   

       58   59    60    61    62   63   64  1   
0     0.0  6.0  13.0  10.0   0.0  0.0  0.0   0  
1     0.0  0.0  11.0  16.0  10.0  0.0  0.0   1  
2     0.0  0.0   3.0  11.0  16.0  9.0  0.0   2  
3     0.0  7.0  13.0  13.0   9.0  0.0  0.0   3  
4     0.0  0.0   2.0  16.0   4.0  0.0  0.0   4  
...   ...  ...   ...   ...   ...  ...  ...  ..  
1792  0.0  2.0  14.0  15.0   9.0  0.0  0.0   9  
1793  0.0  6.0  16.0  14.0   6.0  0.0  0.0   0  
1794  0.0  2.0   9.0  13.0   6.0  0.0  0.0   8  
1795  0.0  5.0  12.0  16.0  12.0  0.0  0.0   9  
1796  1.0  8.0  12.0  14.0  12.0  1.0  0.0   8  

[1797 rows x 65 columns]

In [33]:
["f%d" % i for i in range(1, 20)]

['f1',
 'f2',
 'f3',
 'f4',
 'f5',
 'f6',
 'f7',
 'f8',
 'f9',
 'f10',
 'f11',
 'f12',
 'f13',
 'f14',
 'f15',
 'f16',
 'f17',
 'f18',
 'f19']

In [34]:
import numpy as np
X = np.array([[-1, -1], [-2, -1], [1, 1], [2, 1]])
y = np.array([1, 1, 2, 2])
from sklearn.svm import SVC
clf = SVC(gamma='auto')
clf.fit(X, y)

print(clf.predict([[-0.8, -1]]))

[1]


In [36]:
X.var?